# select CAR_ID, AVAILABILITY
# from (
#     select CAR_ID, '대여중' as AVAILABILITY
#     from CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     group by CAR_ID
#     having END_DATE >= '2022-10-16', START_DATE <= '2022-10-16'

# )

# SELECT DISTINCT CAR_ID, '대여중' as AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'

SELECT 
    CAR_ID,
    MAX(CASE 
        WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
        ELSE '대여 가능' 
    END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;