SELECT 
    a.AUTHOR_ID, 
    c.AUTHOR_NAME, 
    a.CATEGORY, 
    SUM(b.SALES * a.PRICE) AS TOTAL_SALES
FROM BOOK AS a
LEFT JOIN BOOK_SALES AS b
    ON a.BOOK_ID = b.BOOK_ID
LEFT JOIN AUTHOR AS c
    ON a.AUTHOR_ID = c.AUTHOR_ID
WHERE b.SALES_DATE LIKE '2022-01%'
GROUP BY 
    a.AUTHOR_ID, 
    a.CATEGORY
order by a.AUTHOR_ID asc, a.CATEGORY desc